export const links = [
    {
        id:1,
        text:'home',
        url:'#home'
    },
    {
        id:2,
        text:'about',
        url:'#about'
    },
    {
        id:3,
        text:'products',
        url:'#products'
    },
    {
        id:4,
        text:'services',
        url:'#services'
    },
    {
        id:5,
        text:'team',
        url:'#team'
    },
    {
        id:6,
        text:'contact',
        url:'#contact'
    },
]